version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/.pnpm-store/v3
    env_file:
      - .env.local
    environment:
      NODE_ENV: development
    command: pnpm run dev
